2025-04-19 10:51:35,368 INFO: Sistema de logging inicializado [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:64]
2025-04-19 10:52:44,841 INFO: Sistema de logging inicializado [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:64]
2025-04-19 10:53:27,282 INFO: Sistema de logging inicializado [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:64]
2025-04-19 10:54:33,491 INFO: Sistema de logging inicializado [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:64]
2025-04-19 10:55:08,317 INFO: Sistema de logging inicializado [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:64]
2025-04-19 10:56:32,024 INFO: Locating template 'index.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - C:\Users\Jorge Maques\Documents\Diabetes\templates
       -> found ('C:\\Users\\Jorge Maques\\Documents\\Diabetes\\templates\\index.html') [in C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\debughelpers.py:178]
2025-04-19 10:56:41,814 INFO: Locating template 'test_results.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - C:\Users\Jorge Maques\Documents\Diabetes\templates
       -> found ('C:\\Users\\Jorge Maques\\Documents\\Diabetes\\templates\\test_results.html') [in C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\debughelpers.py:178]
2025-04-19 10:57:56,220 INFO: Iniciando processamento de formulário [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:81]
2025-04-19 10:57:56,503 INFO: Locating template 'results.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - C:\Users\Jorge Maques\Documents\Diabetes\templates
       -> found ('C:\\Users\\Jorge Maques\\Documents\\Diabetes\\templates\\results.html') [in C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\debughelpers.py:178]
2025-04-19 11:26:46,660 INFO: Locating template 'test_results.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - C:\Users\Jorge Maques\Documents\Diabetes\templates
       -> found ('C:\\Users\\Jorge Maques\\Documents\\Diabetes\\templates\\test_results.html') [in C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\debughelpers.py:178]
2025-04-19 11:26:46,732 ERROR: Erro no test_model: 'probabilidade' is undefined [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:165]
Traceback (most recent call last):
  File "C:\Users\Jorge Maques\Documents\Diabetes\app.py", line 162, in test_model
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jorge Maques\Documents\Diabetes\templates\test_results.html", line 40, in top-level template code
    {% if probabilidade > 80 %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'probabilidade' is undefined
2025-04-19 11:27:46,013 INFO: Locating template 'test_results.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - C:\Users\Jorge Maques\Documents\Diabetes\templates
       -> found ('C:\\Users\\Jorge Maques\\Documents\\Diabetes\\templates\\test_results.html') [in C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\debughelpers.py:178]
2025-04-19 11:27:46,024 ERROR: Erro no test_model: 'result' is undefined [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:165]
Traceback (most recent call last):
  File "C:\Users\Jorge Maques\Documents\Diabetes\app.py", line 162, in test_model
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jorge Maques\Documents\Diabetes\templates\test_results.html", line 40, in top-level template code
    {% if result['Probabilidade'] > 80 %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 471, in getitem
    return obj[argument]
           ~~~^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'result' is undefined
2025-04-19 11:28:16,209 INFO: Locating template 'test_results.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - C:\Users\Jorge Maques\Documents\Diabetes\templates
       -> found ('C:\\Users\\Jorge Maques\\Documents\\Diabetes\\templates\\test_results.html') [in C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\debughelpers.py:178]
2025-04-19 11:28:16,213 ERROR: Erro no test_model: expected token ':', got '}' [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:165]
Traceback (most recent call last):
  File "C:\Users\Jorge Maques\Documents\Diabetes\app.py", line 162, in test_model
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jorge Maques\Documents\Diabetes\templates\test_results.html", line 40, in template
    {% if {{ result['Probabilidade'] }} > 80 %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateSyntaxError: expected token ':', got '}'
2025-04-19 11:29:45,302 INFO: Locating template 'test_results.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - C:\Users\Jorge Maques\Documents\Diabetes\templates
       -> found ('C:\\Users\\Jorge Maques\\Documents\\Diabetes\\templates\\test_results.html') [in C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\debughelpers.py:178]
2025-04-19 11:29:45,305 ERROR: Erro no test_model: expected token ':', got '}' [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:165]
Traceback (most recent call last):
  File "C:\Users\Jorge Maques\Documents\Diabetes\app.py", line 162, in test_model
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jorge Maques\Documents\Diabetes\templates\test_results.html", line 40, in template
    {% if {{ result['Probabilidade'] }} > 80 %}:
    ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateSyntaxError: expected token ':', got '}'
2025-04-19 11:32:11,113 INFO: Locating template 'test_results.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - C:\Users\Jorge Maques\Documents\Diabetes\templates
       -> found ('C:\\Users\\Jorge Maques\\Documents\\Diabetes\\templates\\test_results.html') [in C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\debughelpers.py:178]
2025-04-19 11:32:11,118 ERROR: Erro no test_model: expected token ':', got '}' [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:165]
Traceback (most recent call last):
  File "C:\Users\Jorge Maques\Documents\Diabetes\app.py", line 162, in test_model
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jorge Maques\Documents\Diabetes\templates\test_results.html", line 55, in template
    {% if {{ result['Probabilidade'] }} > 80 %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateSyntaxError: expected token ':', got '}'
2025-04-19 11:33:46,273 INFO: Locating template 'test_results.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - C:\Users\Jorge Maques\Documents\Diabetes\templates
       -> found ('C:\\Users\\Jorge Maques\\Documents\\Diabetes\\templates\\test_results.html') [in C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\debughelpers.py:178]
2025-04-19 11:33:46,282 ERROR: Erro no test_model: expected token ':', got '}' [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:165]
Traceback (most recent call last):
  File "C:\Users\Jorge Maques\Documents\Diabetes\app.py", line 162, in test_model
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jorge Maques\Documents\Diabetes\templates\test_results.html", line 55, in template
    {% if {{ result['Probabilidade'] }} > 80 %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateSyntaxError: expected token ':', got '}'
2025-04-19 11:34:54,484 INFO: Locating template 'test_results.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - C:\Users\Jorge Maques\Documents\Diabetes\templates
       -> found ('C:\\Users\\Jorge Maques\\Documents\\Diabetes\\templates\\test_results.html') [in C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\debughelpers.py:178]
2025-04-19 11:34:54,497 ERROR: Erro no test_model: '>' not supported between instances of 'str' and 'int' [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:165]
Traceback (most recent call last):
  File "C:\Users\Jorge Maques\Documents\Diabetes\app.py", line 162, in test_model
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Jorge Maques\Documents\Diabetes\templates\test_results.html", line 55, in top-level template code
    {% if result['Probabilidade'] > 80 %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'str' and 'int'
2025-04-19 11:39:00,190 INFO: Locating template 'test_results.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - C:\Users\Jorge Maques\Documents\Diabetes\templates
       -> found ('C:\\Users\\Jorge Maques\\Documents\\Diabetes\\templates\\test_results.html') [in C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\debughelpers.py:178]
2025-04-19 11:41:15,545 INFO: Sistema de logging inicializado [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:64]
2025-04-19 11:41:22,195 INFO: Sistema de logging inicializado [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:64]
2025-04-19 11:41:30,351 INFO: Sistema de logging inicializado [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:64]
2025-04-19 11:41:37,257 INFO: Sistema de logging inicializado [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:64]
2025-04-19 11:41:52,382 INFO: Sistema de logging inicializado [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:64]
2025-04-19 11:43:38,357 INFO: Locating template 'index.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - C:\Users\Jorge Maques\Documents\Diabetes\templates
       -> found ('C:\\Users\\Jorge Maques\\Documents\\Diabetes\\templates\\index.html') [in C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\debughelpers.py:178]
2025-04-19 11:44:40,293 INFO: Iniciando processamento de formulário [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:81]
2025-04-19 11:44:40,494 INFO: Predição realizada - Resultado: 1, Probabilidade: 90.83% [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:114]
2025-04-19 11:44:40,496 INFO: Locating template 'results.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - C:\Users\Jorge Maques\Documents\Diabetes\templates
       -> found ('C:\\Users\\Jorge Maques\\Documents\\Diabetes\\templates\\results.html') [in C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\debughelpers.py:178]
2025-04-19 11:47:21,685 INFO: Iniciando processamento de formulário [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:81]
2025-04-19 11:47:21,806 INFO: Predição realizada - Resultado: 1, Probabilidade: 78.29% [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:114]
2025-04-19 11:50:44,357 INFO: Locating template 'test_results.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - C:\Users\Jorge Maques\Documents\Diabetes\templates
       -> found ('C:\\Users\\Jorge Maques\\Documents\\Diabetes\\templates\\test_results.html') [in C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\debughelpers.py:178]
2025-04-19 11:58:58,911 INFO: Locating template 'test_results.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - C:\Users\Jorge Maques\Documents\Diabetes\templates
       -> found ('C:\\Users\\Jorge Maques\\Documents\\Diabetes\\templates\\test_results.html') [in C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\debughelpers.py:178]
2025-04-19 12:01:56,345 INFO: Iniciando processamento de formulário [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:81]
2025-04-19 12:01:56,446 INFO: Predição realizada - Resultado: 0, Probabilidade: 3.65% [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:114]
2025-04-19 12:01:56,480 INFO: Locating template 'results.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - C:\Users\Jorge Maques\Documents\Diabetes\templates
       -> found ('C:\\Users\\Jorge Maques\\Documents\\Diabetes\\templates\\results.html') [in C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\debughelpers.py:178]
2025-04-19 12:03:49,566 INFO: Iniciando processamento de formulário [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:81]
2025-04-19 12:03:49,653 INFO: Predição realizada - Resultado: 0, Probabilidade: 33.64% [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:114]
2025-04-19 12:05:49,893 INFO: Iniciando processamento de formulário [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:81]
2025-04-19 12:05:49,974 INFO: Predição realizada - Resultado: 1, Probabilidade: 73.36% [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:114]
2025-04-19 12:07:21,323 INFO: Iniciando processamento de formulário [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:81]
2025-04-19 12:07:21,410 INFO: Predição realizada - Resultado: 1, Probabilidade: 81.61% [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:114]
2025-04-19 12:22:46,001 INFO: Iniciando processamento de formulário [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:81]
2025-04-19 12:22:46,104 INFO: Predição realizada - Resultado: 0, Probabilidade: 24.03% [in C:\Users\Jorge Maques\Documents\Diabetes\app.py:114]
2025-04-19 12:22:46,135 INFO: Locating template 'results.html':
    1: trying loader of application 'app'
       class: jinja2.loaders.FileSystemLoader
       encoding: 'utf-8'
       followlinks: False
       searchpath:
         - C:\Users\Jorge Maques\Documents\Diabetes\templates
       -> found ('C:\\Users\\Jorge Maques\\Documents\\Diabetes\\templates\\results.html') [in C:\Users\Jorge Maques\Documents\Diabetes\venv\Lib\site-packages\flask\debughelpers.py:178]
